apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo-adminservice-cm
  namespace: infra
data:
  application-github.properties: |
    # DataSource
    spring.datasource.url = jdbc:mysql://52.82.117.0:3306/ApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = apolloconfig
    spring.datasource.password = 1qaz@WSX
    eureka.service.url = http://apolloconfig-dev-int.int/eureka
  app.properties: |
    appId=100003172
